### ISSUE TITLE
feat: 分支管理代码

### ISSUE THREAD

**Issue by hunjixin** [jiaozifs/jiaozifs#16]
实现branch 管理接口 可参考lakefs实现

**Comment by Brownjy** [comment]
branch task:
- [ ] list branches
- [ ] create branch
- [ ] get branch
- [ ] delete branch
---
- [ ] reset branch
- [ ] revert branch
- [ ] cherry pick
- [ ] diff branch

**Comment by hunjixin** [comment]
reset/revert/cherry pick目前不需要这个
diff可以直接调用写的commit相关接口获取
